---
version: "2"
linters:
  default: all
  disable:
    - depguard
    # we don't use json with camel-case
    - tagliatelle
    - nolintlint
    # it should improve to support more known patterns
    - varnamelen
    - ireturn
    - revive
    - wrapcheck
    # we prefer inline error handling
    - noinlineerr
    # deprecated, replaced by wsl_v5
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
